package:
  name: state_logger
  version: 0.0.1

source:
  git_rev:
  git_url: https://github.com/austinvhuang/state-logger/

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home:

